server:
  port: 9011

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/

  instance:
    prefer-ip-address: true

zuul:
  routes:
    project-base:
      path: /base/**
      serviceId: project-base

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: project-base
          uri: lb://project-base
          predicates:
            - Path=/base/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive
