server: 
  port: 9002
spring: 
  application:  
    name: project_recruit-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.106.133:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 192.168.106.133
